### ISSUE TITLE
Containers running inside the dind don't have access to the GPU

### ISSUE THREAD

**Issue by tomerkin** [ehfd/nvidia-dind#3]
Hi,
This is a great solution for running an isolated environment inside a docker daemon on the host machine.
Running `nvidia-smi` inside the dind works as expected.
However, when running a container that needs to run inside the dind:
`docker run --rm --name test --gpus=all --runtime=nvidia nvidia/cuda:12.0.1-base-ubuntu22.04 nvidia-smi
`
I get the following error:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #1: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: stat failed: /proc/driver/nvidia/gpus/0000:04:00.0: no such file or directory: unknown.`

**Comment by ehfd** [comment]
Two possibilities:
- `nvidia-dind` itself requires `--privileged` while you are right that the containers within do not.
- The host driver version needs to support the CUDA version. In this case, at least 525.

**Comment by ehfd** [comment]
@tomerkin I have updated the NVIDIA container toolkit versions to latest, which may also have caused `Auto-detected mode as 'legacy' nvidia-container-cli`.
